### ISSUE TITLE
Some Improvements on the Readme

### ISSUE THREAD

**Issue by arnoob16** [adithyapaib/adithyapaib#1]
### Description
Social media icons aren't `clearly` visible in the Dark mode.

### How to fix 
Pick a color that looks good on both dark & light backgrounds.

### Screenshot
![Untitled](https://user-images.githubusercontent.com/49037005/103521461-d200d000-4e9e-11eb-8557-dd3553ba671c.png)

**Comment by adithyapaib** [comment]
Sure will fix It 
Thanks
